Update firefox pipeline.yml

diff --git a/.github/workflows/firefox pipeline.yml b/.github/workflows/firefox pipeline.yml
--- a/.github/workflows/firefox pipeline.yml
+++ b/.github/workflows/firefox pipeline.yml
@@ -26,7 +26,7 @@ jobs:
       - name: find chrome browser
         run: |
          echo "finding chrome executable in system"
-         which google-chrome || echo "chrome not found"
+         which chromedriver || echo "chrome not found"
          cd /usr/bin
          ls
       
